[package]
name = "planet-maiko"
version = "0.1.0"
description = "Planet Maiko desktop shell"
edition = "2021"
license = "AGPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
